### ISSUE TITLE
LoadEntites bug on vc-platform 3.400

### ISSUE THREAD

**Issue by ayouboss** [VirtoCommerce/vc-module-notification#139]
System.TypeLoadException: Method 'LoadEntities' in type 'VirtoCommerce.NotificationsModule.Data.Services.NotificationLayoutService' from assembly 'VirtoCommerce.NotificationsModule.Data, Version=3.219.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. at VirtoCommerce.NotificationsModule.Web.Module.Initialize(IServiceCollection serviceCollection) at VirtoCommerce.Platform.Modules.ModuleInitializer.Initialize(ModuleInfo moduleInfo) in /home/runner/work/vc-platform/vc-platform/src/VirtoCommerce.Platform.Modules/ModuleInitializer.cs:line 74

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8419 has been created

**Comment by OlegoO** [comment]
Please update all modules to 3.400. You can find more details here: https://www.virtocommerce.org/t/update-path-for-virto-commerce-3-400/605
