### ISSUE TITLE
How can I add contact us page functionality in virto commerce 

### ISSUE THREAD

**Issue by Shagun-Bansal** [VirtoCommerce/vc-module-notification#87]
I found a liquid file for the design of contact us page but when I am trying to send a query from that page I am not able to send the email . In the virto commerce platform I found a notification type as "sending custom form from storefront" which is basically for contact us page but not able to find the implementation of this notification type in notification and store module . So can you please guide me where I can find the implementation of "sending custom form from storefront" notification type.
![Screenshot (370)](https://user-images.githubusercontent.com/86394014/125036032-2a17c980-e0b0-11eb-8a18-70f5e5718b10.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7538 has been created

**Comment by OlegoO** [comment]
@Shagun-Bansal 

Here the step to use **Dynamic Notification**. You can reuse it or create a new one.

1. You need to create form 
https://github.com/VirtoCommerce/vc-theme-default/blob/master/templates/page.contact.liquid#L14

2. And submit form to storefront controller 
https://github.com/VirtoCommerce/vc-storefront/blob/master/VirtoCommerce.Storefront/Controllers/CommonController.cs#L59

3. The storefront transforms request to Dynamic Notification Model
https://github.com/VirtoCommerce/vc-storefront/blob/master/VirtoCommerce.Storefront/Domain/Common/ContactUsFormConverter.cs#L9

3. And Call API to Send Notification SendDynamicNotificationAnStoreEmail
https://github.com/VirtoCommerce/vc-storefront/blob/master/VirtoCommerce.Storefront/Controllers/CommonController.cs#L59

Also, check some prerequisites: 
*. Configure SMTP: SMTP or SendGrid
*. Update Sender email in Store > Advanced properties > E-mail settings section
*. Configure Sending custom form from storefront template
*. Submit form and if all is ok, check Send log

**Comment by Shagun-Bansal** [comment]
@OlegoO  Thank you so much for replying .
Yes I did all these steps that you mentioned and then I checked the send log there it is showing me some error that from ,to ,body and subject must not be null . As I debug the code so I found that it is trying to get some template from somewhere and that template is coming as null. So can you please help me to find this template thing.
![Screenshot (374)](https://user-images.githubusercontent.com/86394014/125053070-47ee2a00-e0c2-11eb-8f9a-e74bd799abc8.png)

**Comment by OlegoO** [comment]
@Shagun-Bansal Could you clarify what's null? template? and what's in the Templates collection?

**Comment by Shagun-Bansal** [comment]
Yes template is null and templates is defined as - public IList<NotificationTemplate> Templates { get; set; } in notification.cs class and I am getting templates also null.
and this is the NotificationTemplate class
![Screenshot (376)](https://user-images.githubusercontent.com/86394014/125054698-1e360280-e0c4-11eb-9c20-39e450eee11d.png)

**Comment by OlegoO** [comment]
@Shagun-Bansal  it's bug, thx for feedback, I reproduced it

**Comment by Shagun-Bansal** [comment]
@OlegoO Thank you for informing me about the bug and can you please also let me know from where we are fetching these from , to ,cc, bcc values because I am getting null in those values but I set the store email and store admin email in the platform for my store but it is not taking that.
![Screenshot (374)](https://user-images.githubusercontent.com/86394014/125066239-63603180-e0d0-11eb-864a-dd1e67b81d0a.png)

**Comment by tatarincev** [comment]
You must pass an existing notification type with the `NotificationRequest .Type` property,  in the  in case of sending  dynamic notification with this API method https://github.com/VirtoCommerce/vc-module-notification/blob/dev/src/VirtoCommerce.NotificationsModule.Web/Controllers/NotificationsController.cs#L188

Please check the value of  `NotificationRequest .Type` for received request object, and check if you have registered notification with that type. 

There is a sample code on how to register a new notification type.
https://github.com/VirtoCommerce/vc-module-notification/blob/dev/samples/VirtoCommerce.NotificationsSampleModule.Web/Module.cs#L59

**Comment by Shagun-Bansal** [comment]
@tatarincev The code that I am using is calling some other api (send/dynamicNotification) but the link that you shared is calling some other api so am I using some wrong code or old code ? Can you please clear this point
![Screenshot (377)](https://user-images.githubusercontent.com/86394014/125067792-547a7e80-e0d2-11eb-8c56-d3c4b0670792.png)

**Comment by tatarincev** [comment]
Please forget my post, I was mistaken. I confirm with @OlegoO  that this is a bug with the fill properties for dynamic notification.

**Comment by Shagun-Bansal** [comment]
@tatarincev ok thanks for telling me.

**Comment by OlegoO** [comment]
@Shagun-Bansal  
To should be fetched from site administrator email
From - from the current account (or from form)
BC, CC from template

**Comment by Shagun-Bansal** [comment]
@OlegoO  yes I added the store email and store admin email in the store on virto platform but still it is not fetching it and showing me null in to field and same with from . And I also added a default template in the "sending custom form from storefront" notification type in virto platform itself and in that I added cc, bcc and subject but still I am getting null in these fields in the code

**Comment by OlegoO** [comment]
@Shagun-Bansal  I said it's a bug - the data is not populated properly, forwarded to operation team, I hope will have more details soon

**Comment by Shagun-Bansal** [comment]
@OlegoO oh ok thank you so much .

**Comment by OlegoO** [comment]
@Shagun-Bansal  please update vc-module-store
https://github.com/VirtoCommerce/vc-module-store/releases/tag/3.20.0

**Comment by Shagun-Bansal** [comment]
@OlegoO Ok I will do thank you for informing me.

**Comment by Shagun-Bansal** [comment]
@OlegoO I tried with the new store module and getting this error now 
![Screenshot (382)](https://user-images.githubusercontent.com/86394014/125600098-04cfa3f0-7926-4156-8a8e-907a40555178.png)
Do I need to make some other changes to make it work?

**Comment by OlegoO** [comment]
Go to stores > store > notifications and create a template for Sending custom form from storefront


![image](https://user-images.githubusercontent.com/7639413/125624642-108ce6f8-f5b9-4a8a-b499-6d7d17caa71b.png)

**Comment by Shagun-Bansal** [comment]
@OlegoO Thank you ,it is working now

**Comment by OlegoO** [comment]
@Shagun-Bansal  you are welcome
